# Generated by Django 5.2 on 2025-10-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('articulos_extra', 'Articulos extra'), ('agua_litros', 'Agua por Litros'), ('botella_20l', 'Botella 20L'), ('botella_10l', 'Botella 10L'), ('botella_5l', 'Botella 5L')], default='agua_litros', max_length=20),
        ),
    ]
